<?php
require_once '../config/db.php';
require_once '../includes/header.php';

$errors  = [];
$success = '';
$new_patient_id = 0;
$fud_label = '';

// Preselected patient comes via POST (from list/view pages)
$preselect = (int)($_POST['patient_id'] ?? 0);

// Get patients list for dropdown
$patients = $conn->query("SELECT patient_id, name FROM patients ORDER BY name");

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['_action']) && $_POST['_action'] === 'save') {
    $patient_id       = (int)($_POST['patient_id'] ?? 0);
    $visit_date       = trim($_POST['visit_date'] ?? '');
    $consultation_fee = (float)($_POST['consultation_fee'] ?? 0);
    $lab_fee          = (float)($_POST['lab_fee'] ?? 0);

    if (!$patient_id)       $errors[] = 'Please select a patient.';
    if (empty($visit_date)) $errors[] = 'Visit date is required.';

    if (empty($errors)) {
        // ── follow_up_due is a GENERATED column (visit_date + 7 days, done by SQL) ──
        $stmt = $conn->prepare("INSERT INTO visits (patient_id, visit_date, consultation_fee, lab_fee) VALUES (?, ?, ?, ?)");
        $stmt->bind_param('isdd', $patient_id, $visit_date, $consultation_fee, $lab_fee);
        if ($stmt->execute()) {
            $new_visit_id   = $stmt->insert_id;
            $new_patient_id = $patient_id;
            // Confirm follow_up_due computed by SQL
            $fud = $conn->query("SELECT DATE_FORMAT(follow_up_due,'%d %b %Y') AS fu FROM visits WHERE visit_id = $new_visit_id")->fetch_assoc();
            $fud_label = $fud['fu'];
            $success = true;
            $preselect = 0;
        } else {
            $errors[] = 'Database error: ' . $conn->error;
        }
    }
}

// Follow-up preview via SQL when visit_date is known
$preview_fu = '';
$posted_visit_date = $_POST['visit_date'] ?? '';
if (!empty($posted_visit_date) && !$success) {
    $vd = $conn->real_escape_string($posted_visit_date);
    $pv = $conn->query("SELECT DATE_FORMAT(DATE_ADD(STR_TO_DATE('$vd','%Y-%m-%d'), INTERVAL 7 DAY),'%d %b %Y') AS fu")->fetch_assoc();
    $preview_fu = $pv['fu'] ?? '';
}
?>

<div class="page-header">
  <h1>Record New Visit</h1>
  <p>Follow-up date is auto-generated by SQL (visit_date + 7 days)</p>
</div>

<?php foreach ($errors as $e): ?>
  <div class="alert alert-error"><?= htmlspecialchars($e) ?></div>
<?php endforeach; ?>

<?php if ($success): ?>
  <div class="alert alert-success">
    Visit recorded! Follow-up auto-set by SQL to <strong><?= htmlspecialchars($fud_label) ?></strong>.
    <!-- POST link to patient view -->
    <form method="POST" action="../patients/view.php" style="display:inline">
      <input type="hidden" name="id" value="<?= $new_patient_id ?>">
      <button type="submit" style="background:none;border:none;color:var(--teal);cursor:pointer;font-weight:600;text-decoration:underline;padding:0">View Patient →</button>
    </form>
  </div>
<?php endif; ?>

<div class="card">
  <form method="POST" action="add.php">
    <!-- Mark this submission as a save action -->
    <input type="hidden" name="_action" value="save">

    <div class="form-grid">
      <div class="form-group">
        <label>Patient *</label>
        <select name="patient_id" required onchange="updatePreview()">
          <option value="">— Select Patient —</option>
          <?php
          $sel_pid = (int)($_POST['patient_id'] ?? $preselect);
          while ($p = $patients->fetch_assoc()):
          ?>
          <option value="<?= $p['patient_id'] ?>" <?= ($sel_pid == $p['patient_id']) ? 'selected' : '' ?>><?= htmlspecialchars($p['name']) ?></option>
          <?php endwhile; ?>
        </select>
      </div>

      <div class="form-group">
        <label>Visit Date *</label>
        <input type="date" name="visit_date" id="visitDate" value="<?= htmlspecialchars($posted_visit_date) ?>" required onchange="updatePreview()">
        <span class="hint" id="fuPreview" style="color:var(--teal);font-weight:600">
          <?= $preview_fu ? "Follow-up due (SQL): $preview_fu" : 'Select date to preview follow-up' ?>
        </span>
      </div>

      <div class="form-group">
        <label>Consultation Fee (₹)</label>
        <input type="number" name="consultation_fee" value="<?= htmlspecialchars($_POST['consultation_fee'] ?? '300') ?>" min="0" step="0.01">
      </div>
      <div class="form-group">
        <label>Lab Fee (₹)</label>
        <input type="number" name="lab_fee" value="<?= htmlspecialchars($_POST['lab_fee'] ?? '0') ?>" min="0" step="0.01">
      </div>
    </div>

    <div class="alert alert-info mt-2">
      <strong>SQL Note:</strong> The <code>follow_up_due</code> column is a <em>GENERATED column</em> in MySQL — it automatically computes <code>DATE_ADD(visit_date, INTERVAL 7 DAY)</code>. No PHP date calculation is used.
    </div>

    <div class="btn-group">
      <button type="submit" class="btn btn-primary">Record Visit</button>
      <a href="../patients/list.php" class="btn btn-outline">Cancel</a>
    </div>
  </form>
</div>

<script>
function updatePreview() {
    const d = document.getElementById('visitDate').value;
    const preview = document.getElementById('fuPreview');
    if (!d) { preview.textContent = 'Select date to preview follow-up'; return; }
    const date = new Date(d);
    date.setDate(date.getDate() + 7);
    const options = { day: '2-digit', month: 'short', year: 'numeric' };
    preview.textContent = 'Follow-up due (SQL): ' + date.toLocaleDateString('en-IN', options);
}
</script>

<?php require_once '../includes/footer.php'; ?>
